In [2]:
import folium
import requests
from pandas import json_normalize

In [ ]:
# 서울 중심 좌표
seoul_coords = [37.5662952, 126.9779451]
# 지도 생성
map = folium.Map(location=seoul_coords, zoom_start=15)

# 마커 추가
folium.Marker(
    location=seoul_coords,
    popup="서울특별시",  # 마커 클릭 시 표시될 글
    tooltip="서울"       # 마우스 오버 시 표시될 글
).add_to(map)


map

In [4]:
targetSite='https://www.starbucks.co.kr/store/getStore.do?r=8K3XF06R9Q'
req=requests.post(targetSite, data={
'ins_lat': 37.563398,
'ins_lng': 126.9863309,
'p_sido_cd': '01',
'p_gugun_cd': '',
'in_biz_cd': '',
'iend': 600,
'set_date': ''
})
starbucks=req.json()
print(type(starbucks))

<class 'dict'>

In [5]:
st_df = json_normalize(starbucks, 'list')
st_df

,seq,sido_cd,sido_nm,gugun_cd,gugun_nm,code_order,view_yn,store_num,sido,gugun,...,t30,t36,t27,t29,t43,t48,z9999,t64,t66,p02
0,0,None,None,None,None,None,None,None,None,None,...,0,0,0,0,0,0,0,0,0,0
1,0,None,None,None,None,None,None,None,None,None,...,0,0,0,0,0,0,0,0,0,0
2,0,None,None,None,None,None,None,None,None,None,...,0,0,0,0,0,0,0,0,0,0
3,0,None,None,None,None,None,None,None,None,None,...,0,0,0,0,0,0,0,0,0,0
4,0,None,None,None,None,None,None,None,None,None,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
595,0,None,None,None,None,None,None,None,None,None,...,0,0,0,0,0,0,0,0,0,0
596,0,None,None,None,None,None,None,None,None,None,...,0,0,0,0,0,0,0,0,0,0
597,0,None,None,None,None,None,None,None,None,None,...,0,0,0,0,0,0,0,0,0,0
598,0,None,None,None,None,None,None,None,None,None,...,0,0,0,0,0,0,0,0,0,0
599,0,None,None,None,None,None,None,None,None,None,...,0,0,0,0,0,0,0,0,0,0

In [6]:
st_df_map = st_df[['s_name','sido_code','sido_name','gugun_code','gugun_name',
                   'doro_address','lat','lot']]
st_df_map.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 600 entries, 0 to 599
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   s_name        600 non-null    object
 1   sido_code     600 non-null    object
 2   sido_name     600 non-null    object
 3   gugun_code    600 non-null    object
 4   gugun_name    600 non-null    object
 5   doro_address  600 non-null    object
 6   lat           600 non-null    object
 7   lot           600 non-null    object
dtypes: object(8)
memory usage: 37.6+ KB

In [8]:
st_df_map['lat'] = st_df_map['lat'].astype(float)
st_df_map['lot'] = st_df_map['lot'].astype(float)

C:\Users\Admin\AppData\Local\Temp\ipykernel_19064\3956451395.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  st_df_map['lat'] = st_df_map['lat'].astype(float)
C:\Users\Admin\AppData\Local\Temp\ipykernel_19064\3956451395.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  st_df_map['lot'] = st_df_map['lot'].astype(float)

In [9]:
st_df_map.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 600 entries, 0 to 599
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   s_name        600 non-null    object
 1   sido_code     600 non-null    object
 2   sido_name     600 non-null    object
 3   gugun_code    600 non-null    object
 4   gugun_name    600 non-null    object
 5   doro_address  600 non-null    object
 6   lat           600 non-null    float64
 7   lot           600 non-null    float64
dtypes: float64(2), object(6)
memory usage: 37.6+ KB

In [49]:
st_df_map.head()

,s_name,sido_code,sido_name,gugun_code,gugun_name,doro_address,lat,lot
0,역삼아레나빌딩,01,서울,0101,강남구,서울특별시 강남구 언주로 425 (역삼동),37.501087,127.043069
1,논현역사거리,01,서울,0101,강남구,서울특별시 강남구 강남대로 538 (논현동),37.510178,127.022223
2,신사역성일빌딩,01,서울,0101,강남구,서울특별시 강남구 강남대로 584 (논현동),37.513931,127.020606
3,국기원사거리,01,서울,0101,강남구,서울특별시 강남구 테헤란로 125 (역삼동),37.499517,127.031495
4,대치재경빌딩,01,서울,0101,강남구,서울특별시 강남구 남부순환로 2947 (대치동),37.494668,127.062583

In [15]:
map = folium.Map(location=[37.5665, 126.9780], zoom_start=10)

# 앞 5개 매장만 선택
for idx, row in st_df_map.head(5).iterrows():
    folium.Marker(
        location=[row['lat'], row['lot']],
        popup=row['s_name'],  # 클릭 시 매장 이름 표시
        tooltip=row['sido_name'] + ' ' + row['gugun_name'],  # 마우스 오버 시 시도+구 표시
    ).add_to(map)
map

In [16]:
map = folium.Map(location=[37.5665, 126.9780], zoom_start=10)

# 모든 스타벅스 매장
for idx, row in st_df_map.iterrows():
    folium.Marker(
        location=[row['lat'], row['lot']]
    ).add_to(map)
map